### PR TITLE
fix: Make parallelism limit configurable and set default to 10

### PR DESCRIPTION
**Pull request by jannfis**
Signed-off-by: jannfis <jann@mistrust.net>

**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:

This PR changes two things:

* Allow setting the `--kubectl-parallelism-limit` option to the `argocd-application-controller` workload using `.spec.controller.parallelismLimit` (which has data type of `int32`)
* Set the default value for all workloads spawned by Operator to `10` (instead of the upstream's `20`), because memory consumption seems way higher with a parallelism of `20`.

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [ ] Documentation has been updated.

Documentation will be updated once we cherry-pick this into master.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

* Create default `ArgoCD` CR
* Observe command line options for `argocd-application-controller` includes `--kubectl-parallelism-limit` with a value of `10`
* Set `.spec.controller.parallelismLimit` to 20
* Observe command line options for `argocd-application-controller` includes `--kubectl-parallelism-limit` with a value of `20`
* Remove `.spec.controller.parallelismLimit` from CR
* Observe command line options for `argocd-application-controller` includes `--kubectl-parallelism-limit` with a value of `10` again

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
let's hold this change until the `operator-sdk upgrade` #298  is merged into the master.

**Comment by jannfis** [comment]
This is a PR against rhos-v1.2 branch, so should not interfere with changes in master branch. Will need a backport one way or the other.

**Comment by iam-veeramalla** [comment]
> This is a PR against rhos-v1.2 branch, so should not interfere with changes in master branch. Will need a backport one way or the other.

my bad !! missed that part.

**Comment by iam-veeramalla** [comment]
@jannfis We might have to port these changes into master branch right ?

**Pull request merged**
