### PR TITLE
fix: Reconcile redis resource limits when HA is enabled

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
When `.spec.ha.enable` is set to `true`, changes to `spec.ha.resources` are not reconciled. This PR fixes the reconciliation by adding checks in redis reconciliation code to check if `spec.ha.resources` in `argocd` cr is updated. 
It also  moves old `tests/ha/1-003_validate_redis_ha` e2e tests to `tests/k8s/1-020_validate_redis_ha_nonha`.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [x] Documentation has been updated.

**How to test changes / Special notes to the reviewer**:
1. Run the operator locally using `make install run`
2. Create argo-cd instance with `ha` enabled
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  ha:
    enabled: true
```
3. Wait for argocd `.status.redis: Running` (takes few minutes for redis pods to come up when ha is enabled).
4. Set resource limits for redis & ha
   `kubectl edit argocd/argocd`
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  ha:
    enabled: true
    resources:
      limits: 
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
```
5. Verify new resource limits are applied
   - redis limits
   ```bash
   # redis limits
   $ kubectl get statefulset.apps/argocd-redis-ha-server -o=jsonpath='{range .spec.template.spec.containers[*]}{.name}: {.resources}{"\n"}{end}'
   redis: {"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"128Mi"}}
   sentinel: {"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"128Mi"}}

   # haproxy limits 
   $ kubectl get deployment.apps/argocd-redis-ha-haproxy -o=jsonpath='{range .spec.template.spec.containers[*]}{.name}: {.resources}{"\n"}{end}'
   haproxy: {"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"200m","memory":"128Mi"}}
   ```
6. e2e test for the PR
   `kubectl kuttl test ./tests/k8s --config ./tests/kuttl-tests.yaml --test 1-020_validate_redis_ha_nonha`

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@svghadi , its looking good overall, were you able to test it on a cluster ?

**Comment by svghadi** [comment]
> What happens when resources are provided in both .spec.ha.resources and .spec.redis.resources ?

limits under `.spec.ha.resources` are applied if ha is enabled.

**Comment by iam-veeramalla** [comment]
ok, @svghadi please ping me once the PR is ready for review

**Review by iam-veeramalla — APPROVED** [review]
Good Work @svghadi , LGTM

**Pull request merged**
