### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by saumeya**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
Can you also update build/utils/Dockerfile ?

**Comment by iam-veeramalla** [comment]
@saumeya did you check if the CRDs should be udpated ?

**Comment by saumeya** [comment]
> @saumeya did you check if the CRDs should be udpated ?

I think they were updated here - https://github.com/argoproj-labs/argocd-operator/pull/1499/files  
how else to check?

**Comment by saumeya** [comment]
> Can you also update build/utils/Dockerfile ?

rebased

**Review by anandf — APPROVED** [review]
LGTM

**Pull request merged**
