### PR TITLE
Upgraded argocd operator version to 0.12.0 to prepare for the next re…

### PR DESCRIPTION
**Pull request by anandf**
…lease

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by reginapizza** [comment]
the `control-plane` labels are wrong on this PR, but could always be updated later just anytime before the release as long as it won't be forgotten. 
If you want to know how to change that now though, the fields that need to change are outlined in the release process doc: https://argocd-operator.readthedocs.io/en/latest/release-process/

**Comment by anandf** [comment]
> the `control-plane` labels are wrong on this PR, but could always be updated later just anytime before the release as long as it won't be forgotten. If you want to know how to change that now though, the fields that need to change are outlined in the release process doc: https://argocd-operator.readthedocs.io/en/latest/release-process/

Updated the relavant manifest files.

**Comment by svghadi** [comment]
I think this also needs an update
https://github.com/argoproj-labs/argocd-operator/blob/b4daa97202efea01194731fc9fd8995219b15186/config/manifests/bases/argocd-operator.clusterserviceversion.yaml#L1421-L1423

**Comment by anandf** [comment]
> I think this also needs an update
> 
> https://github.com/argoproj-labs/argocd-operator/blob/b4daa97202efea01194731fc9fd8995219b15186/config/manifests/bases/argocd-operator.clusterserviceversion.yaml#L1421-L1423

Fixed the replaces and current version.

**Review by svghadi — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
