### PR TITLE
feat: make specifying config-management sidecar plugin image optional

### PR DESCRIPTION
**Pull request by jopit**
**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:

Make specifying the sidecar image for a config-management plugin optional. When the image is not specified the operator will use the product image being used for the repo server.

### CODE REVIEW

**Review by jgwest — CHANGES_REQUESTED** [review]
Looks great, thanks @jopit!

Two quick requests: 
- Can you add a short description of the new behaviour to `docs/usage/config_management_2.0.md`? This looks like the best place to document the change in the code itself.
- Can you likewise add a short description of the behaviour as a comment to `SidecarContainers` field in https://github.com/argoproj-labs/argocd-operator/blob/9174e68766ed748642e0c3207043709a75f7a3a7/api/v1beta1/argocd_types.go#L113 (and also the v1alpha1 API).

I presume we are ALSO documenting this downstream, but it couldn't hurt to include it here too.

**Review by svghadi — APPROVED** [review]
LGTM.

**Comment by svghadi** [comment]
Fixes #923

**Review by jgwest — APPROVED** [review]
LGTM too, thanks again @jopit!

**Pull request merged**
