### PR TITLE
feat: add default nodeSelector for linux in workloads

### PR DESCRIPTION
**Pull request by saumeya**
Signed-off-by: saumeya <saumeyakatyal@gmail.com>

**What type of PR is this?**
 /kind enhancement

**What does this PR do / why we need it**:
This PR adds default nodeSelector for running argoCD pod only on Linux nodes.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:
```make install run``` , check the nodeSelectors added to the deployments by default.

### CODE REVIEW

**Comment by jannfis** [comment]
Can you please add some kuttl tests around this?

**Comment by saumeya** [comment]
> Can you please add some kuttl tests around this?

Added

**Review by iam-veeramalla — APPROVED** [review]
@saumeya Thanks, LGTM

**Comment by saumeya** [comment]
> @saumeya Thanks, LGTM

Thanks for reviewing @iam-veeramalla , could you merge?

**Pull request merged**
