### PR TITLE
chore: upgrade operator-sdk to 1.35.0 and migrate kubebuilder go/v3 to go/v4

### PR DESCRIPTION
**Pull request by saumeya**
**What type of PR is this?**
 /kind chore

**What does this PR do / why we need it**:

This PR upgrades the current operator to use operator-sdk 1.35 and kubebuilder go/v4.
This is needed to keep the operator up to date with the latest dependencies

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by saumeya** [comment]
This PR includes the changes in https://github.com/argoproj-labs/argocd-operator/pull/1447 which was only upgrading it to operator-sdk 1.32

With this PR, the migration from kubebuilder go/v3 to go/v4 is also added.

The operator has been tested and passes with these steps as well - https://github.com/argoproj-labs/argocd-operator/tree/master/tests/olm#build-and-install-the-operator

**Review by jgwest — APPROVED** [review]
Looks great, thanks @saumeya!

**Review by ishitasequeira — APPROVED** [review]
Lgtm!!

**Comment by anandrkskd** [comment]
LGTM

**Review by svghadi — APPROVED** [review]
LGTM. Thanks @saumeya

**Pull request merged**
