### PR TITLE
fix: GITOPS-4183 [Bug RC-v1.12.0-3] `Create Job` from ArgoCD UI fails

### PR DESCRIPTION
**Pull request by chengfang**
**What type of PR is this?**
 /kind bug

**What does this PR do / why we need it**:
https://issues.redhat.com/browse/GITOPS-4183
[Bug RC-v1.12.0-3] `Create Job` from ArgoCD UI fails

This is a follow-up fix to #1219 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by svghadi** [comment]
@chengfang - I have added the required fix for appset tests in this PR. The tests are passing now.

**Review by svghadi — APPROVED** [review]

**Review by iam-veeramalla — APPROVED** [review]

**Comment by svghadi** [comment]
/release-0.9

**Pull request merged**
