### PR TITLE
Add host attribute to SSO provider spec

### PR DESCRIPTION
**Pull request by Rizwana777**
JIRA - https://issues.redhat.com/browse/GITOPS-1737

### CODE REVIEW

**Review by jgwest — CHANGES_REQUESTED** [review]

**Comment by jgwest** [comment]
When I run `make test` on master branch, the tests pass without any issue, so the test failures are likely due to changes on this PR.

**Comment by Rizwana777** [comment]
> When I run `make test` on master branch, the tests pass without any issue, so the test failures are likely due to changes on this PR.

yes, I updated the tests, PTAL

**Comment by Rizwana777** [comment]
> > When I run `make test` on master branch, the tests pass without any issue, so the test failures are likely due to changes on this PR.
> 
> yes, I updated the tests and tests are passing, PTAL

**Review by jgwest — APPROVED** [review]
LGTM, thanks @Rizwana777!

**Pull request merged**
