### PR TITLE
Rebase master with 0.10.0 and 0.9.1 releases

### PR DESCRIPTION
**Pull request by reginapizza**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by jgwest — CHANGES_REQUESTED** [review]
Hey, what is this PR for? The list of commits looks scary :sweat_smile:

**Comment by reginapizza** [comment]
@jgwest yes, I agree :') I was rebasing the master branch with the changes in the release-0.10.0 branch. After I released 0.10.0 I didn't update the master branch right away (slipped my mind with vacation and the amount of time it took to get the olm catalog PR's merged- my bad) but it seems like there were a lotttt of other changes also not synced to master branch from 0.10.0? I've already taken a look at the 0.10.0 changes that I made and I think there's okay, but I've requested Anand and Abhishek's to make sure everything else looks right before we consider merging it. If you also wouldn't mind taking a look, the more eyes on it the better!

**Comment by jgwest** [comment]
@reginapizza Strangely, the 'Files Changed' tab of this PR seems to be reported changes to `master` branch that are already on `master` branch.

**Comment by reginapizza** [comment]
Okay I re-synced from master again (I can see I pulled from it originally, so I'm not really sure why it did all those commits over again) and now I think it looks much better! Thanks for the tip @jgwest

**Review by anandf — APPROVED** [review]
LGTM

**Comment by reginapizza** [comment]
fyi- just updated this to also included the OLM manifests for the 0.9.1 release as well since those were also missing from master

**Comment by anandf** [comment]
Generated Code step is failing as there is diff reported in `make bundle`. @reginapizza Can you please take a look ?

**Review by jgwest — APPROVED** [review]
LGTM, thanks @reginapizza!

**Pull request merged**
