### PR TITLE
fix: add missing seccompProfile to comply with restricted policy

### PR DESCRIPTION
**Pull request by hamidos**
**What type of PR is this?**

 /kind bug

**What does this PR do / why we need it**:

Add missing seccompProfile to comply with restricted policy

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

#1492

### CODE REVIEW

**Comment by hamidos** [comment]
Hello @svghadi , Thank you for your feedback. 
I did fix the code-gen CI job, and also added the seccompProfile to the argocd components `applicationset`, `dex`, `notifications`, `redis` and `exporter job` .

**Comment by svghadi** [comment]
Awesome. I will run some local tests to see if any other deployment needs seccompProfile.

**Comment by svghadi** [comment]
Ran some tests, the change looks good. We are still missing `securityContext` for keycloak deployment, can we handle that in this PR?

```bash
$ kubectl label --overwrite --dry-run=server ns test pod-security.kubernetes.io/enforce=restricted
Warning: existing pods in namespace "test" violate the new PodSecurity enforce level "restricted:latest"
Warning: keycloak-6b8bbb786d-zrssz: allowPrivilegeEscalation != false, unrestricted capabilities, runAsNonRoot != true, seccompProfile
namespace/test labeled (server dry run)
```

The changes will probably need to be made in 2 places for keycloak: 
- https://github.com/argoproj-labs/argocd-operator/blob/f8b8fab31f9df9f1a47f40e11b1b09879fe19e21/controllers/argocd/keycloak.go#L199
- https://github.com/argoproj-labs/argocd-operator/blob/f8b8fab31f9df9f1a47f40e11b1b09879fe19e21/controllers/argocd/keycloak.go#L593

**Comment by hamidos** [comment]
Hello @svghadi, 
I've added the security context for keycloak deployment.
It would be a good idea to enable restricted profile in the namespace while doing the E2E KUTTL tests.

**Comment by svghadi** [comment]
Yes, sounds good. However, it seems that KUTTL doesn't support adding labels to the namespaces it automatically creates during tests, which happens for most of our tests. Maybe we could create a new test that manually creates a namespace with the required pod security labels, deploys an ArgoCD CR in it, and then runs the tests.

**Review by svghadi — APPROVED** [review]
LGTM. Thanks @hamidos for the contribution.

**Pull request merged**
