### PR TITLE
code-refactoring: Replace ArgoCD v1alpha1 references with v1beta1

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**
/kind code-refactoring

**What does this PR do / why we need it**:
Follow up PR for https://github.com/argoproj-labs/argocd-operator/pull/999 to replace v1alpha1 references of ArgoCD to v1beta1 in operator-redesign branch.

Change:
Update the ArgoCD API import path & references to use 
- `argoproj` for v1beta1
- `argoprojv1alpha1` for v1alpha1

### CODE REVIEW

**Comment by svghadi** [comment]
Most of the changes have already been added to the redesign branch with #1010. However, a few changes are still pending.

**Review by ciiay — COMMENTED** [review]
Hi Siddhesh, all changes look good to me. I only found [this one](https://github.com/argoproj-labs/argocd-operator/blob/operator-redesign/controllers/argocd/keycloak.go#L355) didn't change, is this left on purpose?

**Comment by svghadi** [comment]
Oops, missed it. Thanks for pointing it out. - @ciiay 
Updated the PR.

**Review by ciiay — APPROVED** [review]
LGTM
Thanks 👍

**Pull request merged**
