### PR TITLE
fix: ApplicationSet Controller Does Not Receive Proxy Configuration

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

**What type of PR is this?**
> /kind bug

**What does this PR do / why we need it**:
When using  Operator on Red Hat Openshift 4.7, the argocd-applicationset-controller does not have the global proxy configuration applied.

This causes us to be unable to use ApplicationSet resources due to the following error in the argocd-applicationset-controller logs:
```
Error during fetching repo: `git fetch origin HEAD --tags --force` failed timeout after 1m30s
```

**Have you updated the necessary documentation?**
NA

**Which issue(s) this PR fixes**:
https://github.com/redhat-developer/gitops-operator/issues/249

**How to test changes / Special notes to the reviewer**:
Please refer
https://github.com/redhat-developer/gitops-operator/issues/249

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@wtam2018 can you PTAL and approve :)

**Comment by wtam2018** [comment]
@iam-veeramalla I was trying to understand the problem redhat-developer/gitops-operator#249.  The problem is proxy envs are not propagated from operator to appliationset deployment.  Making the call to `proxyEnvVars()` and set them in applicaionset deployment will fix it. I don't think 
```
	// Global proxy env vars go first
	appSetEnv := []corev1.EnvVar{{
		Name: "NAMESPACE",
		ValueFrom: &corev1.EnvVarSource{
			FieldRef: &corev1.ObjectFieldSelector{
				FieldPath: "metadata.namespace",
			},
		},
	}}
```
has anything to do with the problem.
How did you actually validate the fix?

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla I was trying to understand the problem [redhat-developer/gitops-operator#249](https://github.com/redhat-developer/gitops-operator/issues/249). The problem is proxy envs are not propagated from operator to appliationset deployment. Making the call to `proxyEnvVars()` and set them in applicaionset deployment will fix it. I don't think
> 
> ```
> 	// Global proxy env vars go first
> 	appSetEnv := []corev1.EnvVar{{
> 		Name: "NAMESPACE",
> 		ValueFrom: &corev1.EnvVarSource{
> 			FieldRef: &corev1.ObjectFieldSelector{
> 				FieldPath: "metadata.namespace",
> 			},
> 		},
> 	}}
> ```
> 
> has anything to do with the problem. How did you actually validate the fix?

Hi @wtam2018 , This fix ensures that 
1. Proxy Env Vars are set.
2. Other Env vars of ApplicationSet are Merged with Proxy Env vars in a sorted way. 


I have not done anything new in the fix. I just aligned ApplicationSets with the how other components like Application Controller, Repo Server is working. 
https://github.com/argoproj-labs/argocd-operator/blob/d5c43dc16f46e66db39af661de2f6f8ec936e020/controllers/argocd/deployment.go#L829

**Comment by wtam2018** [comment]
The fix looks good.  Please add unit test.

**Comment by iam-veeramalla** [comment]
Tested it on a proxy cluster and looks fine.
Screenshot 2022-01-20 at 5 21 22 PM

**Review by wtam2018 — APPROVED** [review]
LGTM

**Pull request merged**
