### PR TITLE
Missing syntax-highlighting, toggle button for screen mode in argocd-operator docs

### PR DESCRIPTION
**Pull request by surajyadav1108**
**What type of PR is this?**
docs  enhancement
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

I noticed that the argocd-operator documentation is missing the toggle change button at the top and syntax highlighting for the code blocks, which are present in the argocd-docs. These features provide better ease of use and enhance the overall appearance of the documentation website.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?'
ads code-highlighting and toggle button

**How to test changes / Special notes to the reviewer**:

made changes to the requirement file as the markdown_include module was missing.  #1001

### CODE REVIEW

**Comment by svghadi** [comment]
Thank you @surajyadav1108 for the PR.
 
To approve the PR, we need all CI jobs to pass, including the DCO check. To fix the DCO CI check, please refer the [DCO job](https://github.com/argoproj-labs/argocd-operator/pull/1002/checks?check_run_id=16913379553).

**Comment by surajyadav1108** [comment]
@svghadi forgot to signoff the commits! its ok corrected it you can review now.

**Comment by surajyadav1108** [comment]
@svghadi done

**Comment by svghadi** [comment]
/lgtm
closes https://github.com/argoproj-labs/argocd-operator/issues/1001

**Pull request merged**
