### PR TITLE
update default ArgoCD version to v2.0.0

### PR DESCRIPTION
**Pull request by shubhamagarwal19**
This PR updates the default ArgoCD version from v2.0.0-rc1 to v2.0.0

### CODE REVIEW

**Comment by shubhamagarwal19** [comment]
@jannfis @wtam2018, we should get this merged before the release of argocd-operator v0.0.15 !

**Comment by iam-veeramalla** [comment]
Hi @shubhamagarwal19  @jomkz is on it !! He planned to merge it before the release on friday.

**Comment by jomkz** [comment]
Unfortunately, it is not as simple as updating the hash for the default image version. I need to add a note about this in the developer docs.

The operator is providing the Application and AppProject CRDs that are used by Argo, so those need to be kept updated as well to ensure that the correct CRDs are used that correspond to the version of the operator. I see there there have been changes to [the CRDs](https://github.com/argoproj/argo-cd/tree/master/manifests/crds) since the last update.

I can handle this change if it would be faster but I am not sure if it would be easier for me to update this PR or to close this one out and create a new one?

**Comment by shubhamagarwal19** [comment]
> Unfortunately, it is not as simple as updating the hash for the default image version. I need to add a note about this in the developer docs.
> 
> The operator is providing the Application and AppProject CRDs that are used by Argo, so those need to be kept updated as well to ensure that the correct CRDs are used that correspond to the version of the operator. I see there there have been changes to [the CRDs](https://github.com/argoproj/argo-cd/tree/master/manifests/crds) since the last update.
> 
> I can handle this change if it would be faster but I am not sure if it would be easier for me to update this PR or to close this one out and create a new one?

Hey @jomkz, feel free to open a new one !! Can always reference your PR, the next time we want to upgrade the version !!
I'll close this one !

**Comment by jomkz** [comment]
Thanks @shubhamagarwal19! I will get this in today

**Pull request closed without merging**
