### PR TITLE
Added a environment variable page

### PR DESCRIPTION
**Pull request by ciiay**
**What type of PR is this?**
/kind documentation

**What does this PR do / why we need it**:
There's no environment variable list in the existing documentation.

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:
[GITOPS-2023](https://issues.redhat.com/browse/GITOPS-2023)

Screenshot
Screenshot 2023-03-20 at 3 00 16 PM

### CODE REVIEW

**Comment by ciiay** [comment]
Hi @iam-veeramalla , please review this RP, thanks.

**Comment by iam-veeramalla** [comment]
Can you please add details about the environmental variables support in the Argo CD CR for each component.

For Example:
```
kind: Argo CD
...
...
spec:
  controller:
     env:
       - name: foo
          value: bar
```

**Comment by ciiay** [comment]
Hi @iam-veeramalla , I updated PR as per comment. I still have a question, about the custom environment variables, there’s already a page that has the information. Aren't these env variables part of `ArgoCD`, not part of `argocd-operator`?
https://github.com/argoproj-labs/argocd-operator/blob/master/docs/reference/argocd.md

**Comment by iam-veeramalla** [comment]
> Hi @iam-veeramalla , I updated PR as per comment. I still have a question, about the custom environment variables, there’s already a page that has the information. Aren't these env variables part of `ArgoCD`, not part of `argocd-operator`? https://github.com/argoproj-labs/argocd-operator/blob/master/docs/reference/argocd.md

@ciiay yes there is a page already, do you want to just the page to this new page ?

**Comment by ciiay** [comment]
> > Hi @iam-veeramalla , I updated PR as per comment. I still have a question, about the custom environment variables, there’s already a page that has the information. Aren't these env variables part of `ArgoCD`, not part of `argocd-operator`? https://github.com/argoproj-labs/argocd-operator/blob/master/docs/reference/argocd.md
> 
> @ciiay yes there is a page already, do you want to just the page to this new page ?

As discussed I kept the information on this environment variable page as a good summary of environment variables available on argocd-operator. Thanks for the confirmation.

**Review by iam-veeramalla — APPROVED** [review]
/lgtm
Thanks @ciiay

**Pull request merged**
