### PR TITLE
feat: Publish latest operator image after push to master branch

### LINKED ISSUE #325: Automatically create images with tag `latest` from the master branch
### Is your task related to a problem? Please describe.
The `latest` tag of the image `quay.io/redhat-cop/argocd-operator` is the same as the last release which makes it difficult to continuously verify and test the recent changes before an actual release, especially if there are many changes between two releases.

### Describe the solution you'd like
Create a CI/CD pipeline that automatically creates an image after every commit to the master branch and pushes it into a registry with the tag `latest`. Furthermore, it would be great if this pipeline is also part of the project (e.g. use GitHub Actions).

### Describe alternatives you've considered
Building an image of the master branch by creating my own pipeline.

### PR DESCRIPTION
**Pull request by tylerauerbeck**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind enhancement

**What does this PR do / why we need it**:
This PR adds a GHA workflow to build and publish the latest code to a container registry with the tag `:latest`. It requires three secrets to be created in the repository:
- `REGISTRY_URL` - The registry to publish the image to (i.e. `quay.io/<reponame>`)
- `REGISTRY_USERNAME` - The user to authenticate as
- `REGISTRY_PASSWORD` - The password/token to use to authenticate

This workflow will only run on push/merge to the `master` branch.

**Have you updated the necessary documentation?**

* [X] Documentation update is required by this PR.
* [X] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #325 

**How to test changes / Special notes to the reviewer**:
No great way to test this. But you can see this in action here:

https://github.com/tylerauerbeck/argocd-operator/actions/runs/1024920750

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@tylerauerbeck I was thinking if it would be better to integrate with existing the workflow ?

https://github.com/argoproj-labs/argocd-operator/blob/3c945c648bd056170a494b1a5c8f68e6db6c09fc/.github/workflows/ci-build.yaml#L62

**Comment by tylerauerbeck** [comment]
@iam-veeramalla No problem. Went ahead and added this to the existing workflow. Now it just runs the last few steps only if it sees that a `push` event has happened to the `master` branch. Let me know if you'd like to see anything else.

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla No problem. Went ahead and added this to the existing workflow. Now it just runs the last few steps only if it sees that a `push` event has happened to the `master` branch. Let me know if you'd like to see anything else.

Looks good to me :)

**Review by iam-veeramalla — APPROVED** [review]

**Comment by iam-veeramalla** [comment]
@wtam2018 , @jannfis Do you think it is ok to publish/update the `latest` tag(quay.io/argoproj-labs/argocd-operator) for every commit into master ? Considering there are no e2e tests on this repo.

**Review by jannfis — CHANGES_REQUESTED** [review]
I think it would make more sense to move this into a dedicated workflow, since we don't have the CI workflow failing if the push fails (e.g. on flaky network, quay.io downtime, etc).

**Comment by tylerauerbeck** [comment]
@jannfis No problem. I can revert this last change and put it back in a separate workflow. Just let me know what the final decision is here.

**Comment by iam-veeramalla** [comment]
> @jannfis No problem. I can revert this last change and put it back in a separate workflow. Just let me know what the final decision is here.

@tylerauerbeck apologies, Please proceed with dedicated workflow as Jann suggested.

**Comment by tylerauerbeck** [comment]
@iam-veeramalla No problems. Reverted this change and it is now back in a dedicated workflow.

**Comment by tylerauerbeck** [comment]
@iam-veeramalla Were there any other changes you wanted to see here?

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla Were there any other changes you wanted to see here?

I am good.
/LGTM

**Review by jannfis — APPROVED** [review]
LGTM, thanks @tylerauerbeck !

I have created the appropriate secrets in the repository.

**Comment by tylerauerbeck** [comment]
@jannfis Looks like this is failing because it doesn't have access to push to the repo. So it may either not have the access or it might just be misconfigured. If it's easier to talk about the setup so that we don't leak any credentials, feel free to reach out internally and we can take a look.

**Comment by jannfis** [comment]
Thanks for that offer @tylerauerbeck, will reach out!

**Pull request merged**
