### PR TITLE
feat(argocd): Update controller-runtime for cached namespaces fix

### LINKED ISSUE #337: Multiple ArgoCD Instances in different Namespaces
Using the watched_namespace environment variable I set ArgoCD to watch multiple namespaces such as "argocd-operator-system,org-fdi-system". However while ArgoCD does detect all of the ArgoCD instances I get an issue with the following message:

```sh
unable to get: %v because of unknown namespace for the cache
```

It seems this is related to the following upstream bug:

- https://github.com/kubernetes-sigs/controller-runtime/issues/934

I was just curious as to if any other people have came across this issue and maybe if I myself am doing something wrong. Appreciate any insight you can provide!

### PR DESCRIPTION
**Pull request by sylus**
/kind bug

**What does this PR do / why we need it**:

This updates the controller runtime to support the latest round of bug fixes for multiple namespaces.

**Which issue(s) this PR fixes**:

Fixes #337

### CODE REVIEW

**Comment by sylus** [comment]
Let me know @iam-veeramalla if want any changes :)

**Comment by iam-veeramalla** [comment]
> Let me know @iam-veeramalla if want any changes :)

Sure .. I will have a look :)

**Comment by wtam2018** [comment]
@sylus Thanks for your PR.  Can you please rebase and resolve conflicts.

**Comment by sylus** [comment]
@wtam2018 i rebased again hoping to get this in :) thx!

**Comment by jannfis** [comment]
This may have been superseded by https://github.com/argoproj-labs/argocd-operator/pull/406

**Comment by sylus** [comment]
Unfortunately the namespace issue is still a problem building the latest binary, but I'll try this week to update the P.R.

**Comment by sylus** [comment]
This is rebased it all works just with the bump to controller-runtime to v0.9.5 and I didn't have to do much else. :D

**Comment by sylus** [comment]
@iam-veeramalla @jopit

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla @jopit

@sylus does v0.9.2 not work for you ?

**Review by iam-veeramalla — APPROVED** [review]
Thanks @sylus !!

**Comment by sylus** [comment]
Thanks so much @iam-veeramalla

**Pull request merged**
