### PR TITLE
chore: post release of 0.12.0

### PR DESCRIPTION
**Pull request by saumeya**
**What type of PR is this?**
 /kind chore

**What does this PR do / why we need it**:
This PR involves the post release updates to master after 0.12.0 release. The steps followed are documented here - https://argocd-operator.readthedocs.io/en/latest/release-process/#synchonizing-changes-back-to-master-branch-and-setting-up-the-next-version 
New manifests are created fro the next version release 0.13.0 as well. 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@saumeya can you please add the description.

**Comment by iam-veeramalla** [comment]
@saumeya I think you missed to add the `0.12.0` bundle related changes that went into the `0.12.0` branch to master in this PR. If I am right, we usually copy that folder into the master branch to keep it updated.

**Comment by saumeya** [comment]
> @saumeya I think you missed to add the `0.12.0` bundle related changes that went into the `0.12.0` branch to master in this PR. If I am right, we usually copy that folder into the master branch to keep it updated.

The folder already exists in master, and was done as post release in 0.11 release. What other changes do we need?

**Review by iam-veeramalla — APPROVED** [review]
Thanks @saumeya, LGTM

**Pull request merged**
