### PR TITLE
Update  applicationset crd to v0.2.0

### PR DESCRIPTION
**Pull request by wtam2018**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

The applicationset has not been updated to v0.2.0 even though version/image have been upgraded in default.go.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
This needs to be cherry-picked into rhos-1.3 branch, correct?

**Comment by wtam2018** [comment]
Yes.

**Comment by jannfis** [comment]
Cherry-picked this PR into rhos-v1.3 branch

**Pull request merged**
